version: "3.8"

networks:
    symfony_net:
        driver: overlay

services:
    db:
        image: mysql:9.3
        ports:
            -   "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./config:/etc/mysql/conf.d
            - db_data:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                delay: 5s
        networks:
            - symfony_net

    php:
        image: ghcr.io/noahclemmensen/carmeetsdenmark:latest
        ports:
            - "8000:8000"
        secrets:
            -   firebase_credentials
        environment:
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=9.3"
            APP_ENV: prod
            APP_SECRET: ${APP_SECRET}
            MAILER_DSN: "smtp://mailpit:1025"
            FIREBASE_CREDENTIALS: /run/secrets/firebase_credentials
            FIREBASE_PROJECT_ID: spoked-3ddd2
        volumes:
            - uploads_data:/var/www/public/uploads
            - sessions_data:/var/www/var/sessions
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            restart_policy:
                condition: on-failure
                delay: 5s
        networks:
            - symfony_net

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s

        networks:
            - symfony_net

volumes:
    db_data:
    uploads_data:
    sessions_data:

secrets:
    firebase_credentials:
        external: true   # "external" = created manually with `docker secret create`
