version: "3.8"

networks:
    symfony_net:
        driver: overlay

services:
    db:
        image: mysql:9.3
        ports:
            -   "3306:3306"
        environment:
            MYSQL_DATABASE: carmeetsdenmark
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: admin
            MYSQL_PASSWORD: stikadmin1bajer
        volumes:
            - db_data:/var/lib/mysql
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                delay: 5s
        networks:
            - symfony_net

    php:
        image: ghcr.io/noahclemmensen/carmeetsdenmark:latest
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: "mysql://admin:stikadmin1bajer@db:3306/carmeetsdenmark?serverVersion=9.3"
            APP_ENV: prod
            APP_SECRET: your-app-secret-here
            MAILER_DSN: "smtp://mailpit:1025"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
            restart_policy:
                condition: on-failure
                delay: 5s
        networks:
            - symfony_net

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s

        networks:
            - symfony_net

volumes:
    db_data:

