services:
    db:
        image: mysql:9.3
        container_name: db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ../config:/etc/mysql/conf.d
            - db_data:/var/lib/mysql
        networks:
            - symfony_net

    php:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: php
        restart: always
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=9.3"
            APP_ENV: prod
            APP_SECRET: ${APP_SECRET}
            MAILER_DSN: "smtp://mailpit:1025"
        volumes:
            - uploads_data:/var/www/public/uploads
            - sessions_data:/var/www/var/sessions
        depends_on:
            - db
            - mailpit
        networks:
            - symfony_net

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - symfony_net

networks:
    symfony_net:
        driver: bridge

volumes:
    db_data:
    uploads_data:
    sessions_data:
